version: "3"
services:
  springboot-app:
      container_name: springboot-app
      image: springboot-app
      restart: always
      build: .
      ports:
        - 8081:8080 
      environment:
        MYSQL_HOST: mysqldb
        MYSQL_PORT: 3306
        MYSQL_USER: root
        MYSQL_PASSWORD: admin
      depends_on:
        - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: admin
volumes:
  mysql-volume:
    external: true
